# ElastAlert Configuration
rules_folder: /opt/elastalert/rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: elasticsearch
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2

# Webhook endpoint of backend to auto-create incidents
# Each rule can still override alerting, but we set a default here
alert:
  - post
http_post_url: "http://backend:5000/api/alerts/webhook"
