auditbeat.modules:
# Only using file integrity module which doesn't require audit subsystem
- module: file_integrity
  paths:
  - /etc/passwd
  - /etc/group
  - /etc/shadow
  - /etc/hosts
  - /etc/resolv.conf
  scan_at_start: true
  scan_rate_per_sec: 10
  max_file_size: 10 MiB
  hash_types: [sha1]

# Completely disable all audit subsystem functionality
auditbeat.core.modules: [file_integrity]
auditbeat.max_start_delay: 0

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "auditbeat-%{+yyyy.MM.dd}"

setup.template.settings:
  index.number_of_shards: 1

logging.level: debug
logging.to_stderr: true

# Make sure auditd module is disabled
auditbeat.config.modules:
  path: ""
  
# Disable auditd explicitly
auditbeat.core.audit.enabled: false
